/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/foghornci/foghorn/pkg/apis/foghorn.jenkins.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGitEvents implements GitEventInterface
type FakeGitEvents struct {
	Fake *FakeFoghornV1alpha1
	ns   string
}

var giteventsResource = schema.GroupVersionResource{Group: "foghorn.jenkins.io", Version: "v1alpha1", Resource: "gitevents"}

var giteventsKind = schema.GroupVersionKind{Group: "foghorn.jenkins.io", Version: "v1alpha1", Kind: "GitEvent"}

// Get takes name of the gitEvent, and returns the corresponding gitEvent object, and an error if there is any.
func (c *FakeGitEvents) Get(name string, options v1.GetOptions) (result *v1alpha1.GitEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(giteventsResource, c.ns, name), &v1alpha1.GitEvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitEvent), err
}

// List takes label and field selectors, and returns the list of GitEvents that match those selectors.
func (c *FakeGitEvents) List(opts v1.ListOptions) (result *v1alpha1.GitEventList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(giteventsResource, giteventsKind, c.ns, opts), &v1alpha1.GitEventList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GitEventList{ListMeta: obj.(*v1alpha1.GitEventList).ListMeta}
	for _, item := range obj.(*v1alpha1.GitEventList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gitEvents.
func (c *FakeGitEvents) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(giteventsResource, c.ns, opts))

}

// Create takes the representation of a gitEvent and creates it.  Returns the server's representation of the gitEvent, and an error, if there is any.
func (c *FakeGitEvents) Create(gitEvent *v1alpha1.GitEvent) (result *v1alpha1.GitEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(giteventsResource, c.ns, gitEvent), &v1alpha1.GitEvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitEvent), err
}

// Update takes the representation of a gitEvent and updates it. Returns the server's representation of the gitEvent, and an error, if there is any.
func (c *FakeGitEvents) Update(gitEvent *v1alpha1.GitEvent) (result *v1alpha1.GitEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(giteventsResource, c.ns, gitEvent), &v1alpha1.GitEvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitEvent), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGitEvents) UpdateStatus(gitEvent *v1alpha1.GitEvent) (*v1alpha1.GitEvent, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(giteventsResource, "status", c.ns, gitEvent), &v1alpha1.GitEvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitEvent), err
}

// Delete takes name of the gitEvent and deletes it. Returns an error if one occurs.
func (c *FakeGitEvents) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(giteventsResource, c.ns, name), &v1alpha1.GitEvent{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGitEvents) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(giteventsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.GitEventList{})
	return err
}

// Patch applies the patch and returns the patched gitEvent.
func (c *FakeGitEvents) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GitEvent, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(giteventsResource, c.ns, name, pt, data, subresources...), &v1alpha1.GitEvent{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitEvent), err
}
