/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/foghornci/foghorn/pkg/apis/foghorn.jenkins.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGitEventLists implements GitEventListInterface
type FakeGitEventLists struct {
	Fake *FakeFoghornV1alpha1
	ns   string
}

var giteventlistsResource = schema.GroupVersionResource{Group: "foghorn.jenkins.io", Version: "v1alpha1", Resource: "giteventlists"}

var giteventlistsKind = schema.GroupVersionKind{Group: "foghorn.jenkins.io", Version: "v1alpha1", Kind: "GitEventList"}

// Get takes name of the gitEventList, and returns the corresponding gitEventList object, and an error if there is any.
func (c *FakeGitEventLists) Get(name string, options v1.GetOptions) (result *v1alpha1.GitEventList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(giteventlistsResource, c.ns, name), &v1alpha1.GitEventList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitEventList), err
}

// List takes label and field selectors, and returns the list of GitEventLists that match those selectors.
func (c *FakeGitEventLists) List(opts v1.ListOptions) (result *v1alpha1.GitEventListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(giteventlistsResource, giteventlistsKind, c.ns, opts), &v1alpha1.GitEventListList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitEventListList), err
}

// Watch returns a watch.Interface that watches the requested gitEventLists.
func (c *FakeGitEventLists) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(giteventlistsResource, c.ns, opts))

}

// Create takes the representation of a gitEventList and creates it.  Returns the server's representation of the gitEventList, and an error, if there is any.
func (c *FakeGitEventLists) Create(gitEventList *v1alpha1.GitEventList) (result *v1alpha1.GitEventList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(giteventlistsResource, c.ns, gitEventList), &v1alpha1.GitEventList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitEventList), err
}

// Update takes the representation of a gitEventList and updates it. Returns the server's representation of the gitEventList, and an error, if there is any.
func (c *FakeGitEventLists) Update(gitEventList *v1alpha1.GitEventList) (result *v1alpha1.GitEventList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(giteventlistsResource, c.ns, gitEventList), &v1alpha1.GitEventList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitEventList), err
}

// Delete takes name of the gitEventList and deletes it. Returns an error if one occurs.
func (c *FakeGitEventLists) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(giteventlistsResource, c.ns, name), &v1alpha1.GitEventList{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGitEventLists) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(giteventlistsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.GitEventListList{})
	return err
}

// Patch applies the patch and returns the patched gitEventList.
func (c *FakeGitEventLists) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GitEventList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(giteventlistsResource, c.ns, name, pt, data, subresources...), &v1alpha1.GitEventList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GitEventList), err
}
