/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/foghornci/foghorn/pkg/apis/foghorn.jenkins.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeActionLists implements ActionListInterface
type FakeActionLists struct {
	Fake *FakeFoghornV1alpha1
	ns   string
}

var actionlistsResource = schema.GroupVersionResource{Group: "foghorn.jenkins.io", Version: "v1alpha1", Resource: "actionlists"}

var actionlistsKind = schema.GroupVersionKind{Group: "foghorn.jenkins.io", Version: "v1alpha1", Kind: "ActionList"}

// Get takes name of the actionList, and returns the corresponding actionList object, and an error if there is any.
func (c *FakeActionLists) Get(name string, options v1.GetOptions) (result *v1alpha1.ActionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(actionlistsResource, c.ns, name), &v1alpha1.ActionList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActionList), err
}

// List takes label and field selectors, and returns the list of ActionLists that match those selectors.
func (c *FakeActionLists) List(opts v1.ListOptions) (result *v1alpha1.ActionListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(actionlistsResource, actionlistsKind, c.ns, opts), &v1alpha1.ActionListList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActionListList), err
}

// Watch returns a watch.Interface that watches the requested actionLists.
func (c *FakeActionLists) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(actionlistsResource, c.ns, opts))

}

// Create takes the representation of a actionList and creates it.  Returns the server's representation of the actionList, and an error, if there is any.
func (c *FakeActionLists) Create(actionList *v1alpha1.ActionList) (result *v1alpha1.ActionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(actionlistsResource, c.ns, actionList), &v1alpha1.ActionList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActionList), err
}

// Update takes the representation of a actionList and updates it. Returns the server's representation of the actionList, and an error, if there is any.
func (c *FakeActionLists) Update(actionList *v1alpha1.ActionList) (result *v1alpha1.ActionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(actionlistsResource, c.ns, actionList), &v1alpha1.ActionList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActionList), err
}

// Delete takes name of the actionList and deletes it. Returns an error if one occurs.
func (c *FakeActionLists) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(actionlistsResource, c.ns, name), &v1alpha1.ActionList{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeActionLists) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(actionlistsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ActionListList{})
	return err
}

// Patch applies the patch and returns the patched actionList.
func (c *FakeActionLists) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ActionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(actionlistsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ActionList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ActionList), err
}
