/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ActionListerExpansion allows custom methods to be added to
// ActionLister.
type ActionListerExpansion interface{}

// ActionNamespaceListerExpansion allows custom methods to be added to
// ActionNamespaceLister.
type ActionNamespaceListerExpansion interface{}

// ActionListListerExpansion allows custom methods to be added to
// ActionListLister.
type ActionListListerExpansion interface{}

// ActionListNamespaceListerExpansion allows custom methods to be added to
// ActionListNamespaceLister.
type ActionListNamespaceListerExpansion interface{}

// GitEventListerExpansion allows custom methods to be added to
// GitEventLister.
type GitEventListerExpansion interface{}

// GitEventNamespaceListerExpansion allows custom methods to be added to
// GitEventNamespaceLister.
type GitEventNamespaceListerExpansion interface{}

// GitEventListListerExpansion allows custom methods to be added to
// GitEventListLister.
type GitEventListListerExpansion interface{}

// GitEventListNamespaceListerExpansion allows custom methods to be added to
// GitEventListNamespaceLister.
type GitEventListNamespaceListerExpansion interface{}
