/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/foghornci/foghorn/pkg/apis/foghorn.jenkins.io/v1alpha1"
	scheme "github.com/foghornci/foghorn/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ActionListsGetter has a method to return a ActionListInterface.
// A group's client should implement this interface.
type ActionListsGetter interface {
	ActionLists(namespace string) ActionListInterface
}

// ActionListInterface has methods to work with ActionList resources.
type ActionListInterface interface {
	Create(*v1alpha1.ActionList) (*v1alpha1.ActionList, error)
	Update(*v1alpha1.ActionList) (*v1alpha1.ActionList, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ActionList, error)
	List(opts v1.ListOptions) (*v1alpha1.ActionListList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ActionList, err error)
	ActionListExpansion
}

// actionLists implements ActionListInterface
type actionLists struct {
	client rest.Interface
	ns     string
}

// newActionLists returns a ActionLists
func newActionLists(c *FoghornV1alpha1Client, namespace string) *actionLists {
	return &actionLists{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the actionList, and returns the corresponding actionList object, and an error if there is any.
func (c *actionLists) Get(name string, options v1.GetOptions) (result *v1alpha1.ActionList, err error) {
	result = &v1alpha1.ActionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("actionlists").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ActionLists that match those selectors.
func (c *actionLists) List(opts v1.ListOptions) (result *v1alpha1.ActionListList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ActionListList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("actionlists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested actionLists.
func (c *actionLists) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("actionlists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a actionList and creates it.  Returns the server's representation of the actionList, and an error, if there is any.
func (c *actionLists) Create(actionList *v1alpha1.ActionList) (result *v1alpha1.ActionList, err error) {
	result = &v1alpha1.ActionList{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("actionlists").
		Body(actionList).
		Do().
		Into(result)
	return
}

// Update takes the representation of a actionList and updates it. Returns the server's representation of the actionList, and an error, if there is any.
func (c *actionLists) Update(actionList *v1alpha1.ActionList) (result *v1alpha1.ActionList, err error) {
	result = &v1alpha1.ActionList{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("actionlists").
		Name(actionList.Name).
		Body(actionList).
		Do().
		Into(result)
	return
}

// Delete takes name of the actionList and deletes it. Returns an error if one occurs.
func (c *actionLists) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("actionlists").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *actionLists) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("actionlists").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched actionList.
func (c *actionLists) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ActionList, err error) {
	result = &v1alpha1.ActionList{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("actionlists").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
