/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	foghornjenkinsiov1alpha1 "github.com/foghornci/foghorn/pkg/apis/foghorn.jenkins.io/v1alpha1"
	versioned "github.com/foghornci/foghorn/pkg/client/clientset/versioned"
	internalinterfaces "github.com/foghornci/foghorn/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/foghornci/foghorn/pkg/client/listers/foghorn.jenkins.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ActionListInformer provides access to a shared informer and lister for
// ActionLists.
type ActionListInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ActionListLister
}

type actionListInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewActionListInformer constructs a new informer for ActionList type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewActionListInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredActionListInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredActionListInformer constructs a new informer for ActionList type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredActionListInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FoghornV1alpha1().ActionLists(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FoghornV1alpha1().ActionLists(namespace).Watch(options)
			},
		},
		&foghornjenkinsiov1alpha1.ActionList{},
		resyncPeriod,
		indexers,
	)
}

func (f *actionListInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredActionListInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *actionListInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&foghornjenkinsiov1alpha1.ActionList{}, f.defaultInformer)
}

func (f *actionListInformer) Lister() v1alpha1.ActionListLister {
	return v1alpha1.NewActionListLister(f.Informer().GetIndexer())
}
